export const ORGANIZATION_DEFAULT_SORT = 'name@asc';
export const ORGANIZATION_DEFAULT_PAGE = 1;
export const ORGANIZATION_DEFAULT_PER_PAGE = 10;
export const ORGANIZATION_DEFAULT_AVAILABLE_SORT = ['name', 'createdAt'];
export const ORGANIZATION_DEFAULT_AVAILABLE_SEARCH = ['name'];

export enum ENUM_ORGANIZATION_STATUS_CODE_ERROR {
    ORGANIZATION_IS_INACTIVE_ERROR = 5500,
    ORGANIZATION_NOT_FOUND_ERROR = 5501,
    ORGANIZATION_EXIST_ERROR = 5502,
    ORGANIZATION_ACTIVE_ERROR = 5503,
    ORGANIZATION_USED_ERROR = 5504,
}

export const ORGANIZATION_ACTIVE_META_KEY = 'TenantActiveMetaKey';
