version: '3.9'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 3000:80
    networks:
      - app-network
    depends_on:
      - platform-api

  platform-api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only build development stage from our dockerfile
      target: development
      args:
        JFROG_AUTH_TOKEN: ${JFROG_AUTH_TOKEN}
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      JFROG_AUTH_TOKEN: ${JFROG_AUTH_TOKEN}
    ports:
      - 8080:8080
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    links:
      - postgres
    depends_on:
      - postgres
    command: >
      sh -c "yarn start:dev"

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  app-network:
    name: app-network
    driver: bridge
volumes:
  dbdata:
