version: '3.9'
services:
  platform-api:
    container_name: platform-api
    build:
      dockerfile: Dockerfile
      context: .
      # Only build development stage from our dockerfile
      target: development
      args:
        JFROG_AUTH_TOKEN: ${JFROG_AUTH_TOKEN}
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      JFROG_AUTH_TOKEN: ${JFROG_AUTH_TOKEN}
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 9229:9229
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    restart: unless-stopped
    links:
      - postgres
    depends_on:
      - postgres
    command: >
      sh -c "yarn start:dev"

  postgres:
    container_name: postgres
    image: postgres:14.2
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    restart: unless-stopped

networks:
  app-network:
    name: app-network
    driver: bridge
volumes:
  dbdata:
  node_modules:
