version: 2.1

orbs:
  node: circleci/node@5.0.2
  aws-ecr: circleci/aws-ecr@7.3.0

aliases:
  - &filter_deploy_only_branch
    filters:
      branches:
        only:
          - master

jobs:
  build-lint-test:
    docker:
      - image: cimg/node:18.8
      - image: cimg/postgres:14.4
        environment:
          POSTGRES_DB: ${CIRCLE_PROJECT_REPONAME}
          POSTGRES_USER: ${POSTGRES_USERNAME}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    environment:
      APP_ENV: production
      APP_PORT: 8080
      APP_VERSIONING: true
      APP_HTTP_ON: true
      APP_JOB_ON: false
      APP_CACHE_ON: false
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${CIRCLE_PROJECT_REPONAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_NAME: avo-test
      APP_MODE: secure
      APP_LANGUAGE: en
      APP_TZ: Asia/Jerusalem
      APP_VERSION: 1
      MIDDLEWARE_TOLERANCE_TIMESTAMP: 5m
      MIDDLEWARE_TIMEOUT: 30s
      AUTH_SYSTEM_ADMIN_EMAIL: testadmin@avonow.com
      AUTH_SYSTEM_ADMIN_INITIAL_PASS: Avo12345!
      AUTH_JWT_ACCESS_TOKEN_SECRET_KEY: d642c5dbd0b60377b0f57d1d4eea8fcd5cc5770692d00f775b782611b020514a
      AUTH_JWT_ACCESS_TOKEN_EXPIRED: 30m
      AUTH_JWT_REFRESH_TOKEN_SECRET_KEY: d57386583c918b7608771a85ae880bffe365d613c34ffa5a23f20074dd79e7c0
      AUTH_JWT_REFRESH_TOKEN_EXPIRED: 7d
      AUTH_JWT_REFRESH_TOKEN_REMEMBER_ME_EXPIRED: 30d
      AUTH_JWT_REFRESH_TOKEN_NOT_BEFORE_EXPIRATION: 30m
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run linter
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Yarn Build
          command: yarn build
  build-and-push-image:
    docker:
      - image: cimg/base:2022.02
    steps:
      - run:
          name: 'Setup custom environment variables'
          command: |
            echo 'export CUSTOM_IMAGE_TAG="${CIRCLE_BRANCH//\//-}_${CIRCLE_SHA1:0:7}_$(git log -1 --format=%ct)"' >> $BASH_ENV
      - aws-ecr/build-and-push-image:
          remote-docker-layer-caching: true
          setup-remote-docker: true
          repo: ${CIRCLE_PROJECT_REPONAME}
          tag: ${CUSTOM_IMAGE_TAG}
          extra-build-args: '--build-arg JFROG_AUTH_TOKEN=${JFROG_AUTH_TOKEN}'

workflows:
  workflow:
    jobs:
      - build-lint-test:
          context:
            - ci-migrations-job
            - jfrog-platform
            - cloudinary
            - customerio
            - twilio
            - redis
      - build-and-push-image:
          context:
            - eu-ecr
            - jfrog-platform
          requires:
            - build-lint-test
          <<: *filter_deploy_only_branch
