version: 2.1

orbs:
  node: circleci/node@5.0.2
  aws-ecr: circleci/aws-ecr@7.3.0

jobs:
  build-lint-test:
    docker:
      - image: cimg/node:17.9
      - image: cimg/postgres:14.4
        environment:
          POSTGRES_DB: ${CIRCLE_PROJECT_REPONAME}
          POSTGRES_USER: ${POSTGRES_USERNAME}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    environment:
      APP_ENV: production
      APP_PORT: 8080
      APP_VERSIONING: true
      APP_HTTP_ON: true
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${CIRCLE_PROJECT_REPONAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run linter
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Yarn Build
          command: yarn build
  build-and-push-image:
    docker:
      - image: cimg/base:2022.02
    steps:
      - run:
          name: 'Setup custom environment variables'
          command: |
            echo 'export CUSTOM_IMAGE_TAG="${CIRCLE_BRANCH//\//-}_${CIRCLE_SHA1:0:7}_$(git log -1 --format=%ct)"' >> $BASH_ENV
      - aws-ecr/build-and-push-image:
          remote-docker-layer-caching: true
          setup-remote-docker: true
          repo: ${CIRCLE_PROJECT_REPONAME}
          tag: ${CUSTOM_IMAGE_TAG}
          extra-build-args: '--build-arg JFROG_AUTH_TOKEN=${JFROG_AUTH_TOKEN}'

workflows:
  workflow:
    jobs:
      - build-lint-test:
          context:
            - ci-migrations-job
            - jfrog-platform
            - cloudinary
      - build-and-push-image:
          context:
            - eu-ecr
            - jfrog-platform
          requires:
            - build-lint-test
          filters:
            branches:
              only:
                - development
                - master
                - circleci-config-update-tag-build
