apiVersion: v1
data:
  DD_ENV: staging
  DD_SERVICE: platform
  DD_TAGS: country_code:us
  DD_TRACE_DEBUG: 'true'
  HTTP_HOST: 0.0.0.0
  HTTP_PORT: '3000'
  HTTP_URL: https://platform.us.stg.avoc.io
  MONITORING_ENABLED: 'true'
  NODE_ENV: staging
kind: ConfigMap
metadata:
  name: platform-env-65t8mc8762
  namespace: platform
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: platform
  name: platform
  namespace: platform
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/name: platform
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: platform
  name: platform
  namespace: platform
spec:
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: platform
  template:
    metadata:
      labels:
        app.kubernetes.io/name: platform
    spec:
      containers:
        - name: app
          image: 077970707816.dkr.ecr.eu-west-1.amazonaws.com/platform-api:master-95a2383af3e1bfabdf9ae46e91ef738ad42b685f
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http-port
              protocol: TCP
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: host
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: user
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db
          livenessProbe:
            httpGet:
              path: /health
              port: http-port
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: http-port
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              memory: 1G
            requests:
              cpu: 100m
              memory: 200M
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: platform.us.stg.avoc.io
    kubernetes.io/ingress.class: nginx-public
  name: platform
  namespace: platform
spec:
  rules:
    - host: platform.us.stg.avoc.io
      http:
        paths:
          - backend:
              service:
                name: platform
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - platform.us.stg.avoc.io
