export const GROUP_FUN_FACTS_DEFAULT_PAGE = 0;
export const GROUP_FUN_FACTS_DEFAULT_PER_PAGE = 0;
export const GROUP_FUN_FACTS_DEFAULT_SORT = 'createdAt@asc';
export const GROUP_FUN_FACTS_DEFAULT_AVAILABLE_SORT = [];
export const GROUP_FUN_FACTS_DEFAULT_AVAILABLE_SEARCH = [];
